# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5cd8d205531b5419565e6121816454b5"
name = "xeno-retail"
application_url = "https://6901992db4c6.ngrok-free.app"
embedded = true
handle = "xeno-retail"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "carts/create" ]
  uri = "/webhooks/carts/create"

  [[webhooks.subscriptions]]
  topics = [ "carts/update" ]
  uri = "/webhooks/carts/update"

  [[webhooks.subscriptions]]
  topics = [ "checkouts/create" ]
  uri = "/webhooks/checkouts/create"

  [[webhooks.subscriptions]]
  topics = [ "checkouts/update" ]
  uri = "/webhooks/checkouts/update"

  [[webhooks.subscriptions]]
  topics = [ "checkouts/delete" ]
  uri = "/webhooks/checkouts/delete"

  [[webhooks.subscriptions]]
  topics = [ "customers/create" ]
  uri = "/webhooks/customers/create"

  [[webhooks.subscriptions]]
  topics = [ "customers/update" ]
  uri = "/webhooks/customers/update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "orders/updated" ]
  uri = "/webhooks/orders/update"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/products/create"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products/update"

  [[webhooks.subscriptions]]
  topics = [ "draft_orders/create" ]
  uri = "/webhooks/draft_orders/create"

  [[webhooks.subscriptions]]
  topics = [ "draft_orders/update" ]
  uri = "/webhooks/draft_orders/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_customers,read_orders,read_checkouts,read_draft_orders,write_products"

[auth]
redirect_urls = ["https://6901992db4c6.ngrok-free.app/auth/callback", "https://6901992db4c6.ngrok-free.app/auth/shopify/callback", "https://6901992db4c6.ngrok-free.app/api/auth/callback"]

[pos]
embedded = false
